/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as GamesNewRouteImport } from './routes/games.new'
import { Route as GamesIdIndexRouteImport } from './routes/games.$id.index'
import { Route as GamesIdEditRouteImport } from './routes/games.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdIndexRoute = GamesIdIndexRouteImport.update({
  id: '/games/$id/',
  path: '/games/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdEditRoute = GamesIdEditRouteImport.update({
  id: '/games/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/platforms': typeof PlatformsRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id/': typeof GamesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/platforms': typeof PlatformsRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id': typeof GamesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/platforms': typeof PlatformsRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id/': typeof GamesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genres'
    | '/platforms'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genres'
    | '/platforms'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id'
  id:
    | '__root__'
    | '/'
    | '/genres'
    | '/platforms'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenresRoute: typeof GenresRoute
  PlatformsRoute: typeof PlatformsRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIdEditRoute: typeof GamesIdEditRoute
  GamesIdIndexRoute: typeof GamesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/': {
      id: '/games/$id/'
      path: '/games/$id'
      fullPath: '/games/$id/'
      preLoaderRoute: typeof GamesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/edit': {
      id: '/games/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof GamesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenresRoute: GenresRoute,
  PlatformsRoute: PlatformsRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIdEditRoute: GamesIdEditRoute,
  GamesIdIndexRoute: GamesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
